'TGUI':
  - changed-files:
      - any-glob-to-any-file: 'tgui/**'

'Sound':
  - changed-files:
      - any-glob-to-any-file: '**/*.ogg'

'Mapping':
  - all:
      - changed-files:
          - any-glob-to-any-file: '**/*.dmm'

'Sprites':
  - changed-files:
      - any-glob-to-any-file: '**/*.dmi'

'Outils':
  - changed-files:
      - any-glob-to-any-file: ['.gihub/**', 'tools/**', '.vscode/**', '.bin/**']

'Config':
  - changed-files:
      - any-glob-to-any-file: 'config/**'

'Documentation':
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

'SQL':
  - changed-files:
      - any-glob-to-any-file: 'SQL/**'

'Modularité partielle':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['code/**', 'icons/**', 'sounds/**', '_maps/map_files/**', 'tgui/**']
          - any-glob-to-any-file: 'modular_exostation/**'
      - base-branch: 'master'
      - head-branch: ['!tg-update', '!tg-base']

'Non modulaire':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['code/**', 'icons/**', 'sounds/**', '_maps/map_files/**']
          - all-globs-to-all-files: '!modular_exostation/**'
      - base-branch: 'master'
      - head-branch: ['!tg-update', '!tg-base']

'Mirror (/tg/)':
  - all:
    - base-branch: 'master'
    - head-branch: 'tg-update'

'Traductions':
  - base-branch: 'translate'

'Fix':
  - head-branch: ['^fix', 'fix']

'Feature':
  - head-branch: ['^feature', 'feature']

'Port':
  - head-branch: ['^port', 'port']
